config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/menu', to: 'menu#index'
  get 'contact_us', to: 'contact_us#index'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resource :session, only: [:new, :create, :destroy]
    resources :menu_items
    resources :categories
    resources :menu_types
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :menu_items

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :category
  belongs_to :menu_type

  validates_presence_of :name, :description, :price, :menu_type_id, :category_id
  validates_uniqueness_of :name, scope: :menu_type_id
end

app/models/menu_type.rb
class MenuType < ActiveRecord::Base
  has_many :menu_items

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(strong_params)
      if @category.save
        flash[:category_success] = "#{@category.name} was successfully created!"
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update_attributes(strong_params)
        redirect_to admin_categories_path
      else
        render :edit
      end
    end

    def destroy
      category = Category.find(params[:id])
      category.destroy
      redirect_to admin_categories_path
    end

    private

    def strong_params
      params.require(:category).permit(:name)
    end

  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController

    before_filter :is_admin?

    def index
      
    end

    private

    def is_admin?
      unless cookies.signed[:admin]
        redirect_to new_admin_session_path
      end
    end

  end
end

app/controllers/admin/menu_items_controller.rb
module Admin
  class MenuItemsController < ApplicationController

    def index
      @menu_items = MenuItem.all
    end

    def new
      @menu_item = MenuItem.new
      @menu_types = MenuType.all
      @categories = Category.all
    end

    def create
      @menu_item = MenuItem.new(strong_params)
      if @menu_item.save
        flash[:menu_item_success] = "#{@menu_item.name} was successfully added!"
        redirect_to admin_menu_items_path
      else
        render :new
      end
    end

    def edit
      @menu_item = MenuItem.find(params[:id])
      @menu_types = MenuType.all
      @categories = Category.all
    end

    def update
      @menu_item = MenuItem.find(params[:id])
      if @menu_item.update_attributes(strong_params)
        redirect_to admin_menu_items_path
      else
        render :edit
      end
    end

    def destroy
      menu_item = MenuItem.find(params[:id])
      menu_item.destroy
      redirect_to admin_menu_items_path
    end

    private

    def strong_params
      params.require(:menu_item).permit(
        :name,
        :description,
        :price,
        :menu_type_id,
        :category_id
      )
    end

  end
end

app/controllers/admin/menu_types_controller.rb
module Admin
  class MenuTypesController < ApplicationController

    def index
      @menu_types = MenuType.all
    end

    def new
      @menu_type = MenuType.new
    end

    def create
      @menu_type = MenuType.new(strong_params)
      if @menu_type.save
        flash[:menu_type_success] = "Menu Type: #{@menu_type.name} was successfully created!"
        redirect_to admin_menu_types_path
      else
        render :new
      end
    end

    def edit
      @menu_type = MenuType.find(params[:id])
    end

    def update
      @menu_type = MenuType.find(params[:id])
      if @menu_type.update_attributes(strong_params)
        redirect_to admin_menu_types_path
      else
        render :edit
      end
    end

    def destroy
      menu_type = MenuType.find(params[:id])
      menu_type.destroy
      redirect_to admin_menu_types_path
    end

    private

    def strong_params
      params.require(:menu_type).permit(:name)
    end

  end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < ApplicationController

    def new

    end

    def create
      if authenticated?(params[:username], params[:password])
        cookies.signed[:admin] = {:value => true, :expires => 1.days.from_now}
        flash[:login_success] = "Welcome, admin!"
        redirect_to admin_path
      else
        render :new
      end
    end

    def destroy
      cookies.delete(:admin)
      redirect_to new_admin_session_path
    end

    private

    def authenticated?(username, password)
      username == ENV['USERNAME'] && password == ENV['PASSWORD']
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?

  private

  def logged_in?
    cookies.signed[:admin]
  end

end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController

  def index

  end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    if lunch_menu
      @menu_items = MenuItem.where(menu_type_id: MenuType.find_by(name: "Lunch").id)
      @class = "lunch"
    else
      @menu_items = MenuItem.where(menu_type_id: MenuType.find_by(name: "Dinner").id)
      @class = "dinner"
    end
  end

  private

  def lunch_menu
    params[:type] != "dinner" &&
      Time.parse("08:00:00 -0600") < Time.now &&
      Time.now < Time.parse("15:00:00 -0600") ||
      params[:type] == "lunch"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to menu_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_categories_form.html.erb
<ul>
  <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for @category, url: url do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit button_text %>
<% end %>

app/views/admin/categories/edit.html.erb
<h3>Edit <%= @category.name %></h3>

<%= render partial: "categories_form", locals: {url: "/admin/categories/#{@category.id}", button_text: "Update Category"} %>

app/views/admin/categories/index.html.erb
<div class="categories-container">
  <h1>Categories</h1>

  <%= flash[:category_success] %>

  <%= link_to "Add Category", new_admin_category_path, class: "main-link" %>

  <table>
    <thead>
    <th>Name</th>
    <th></th>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to "Edit", edit_admin_category_path(category), class: "main-button" %>
          <%= link_to "Delete", admin_category_path(category), method: :delete, class: "main-button" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<h1>Create a Category</h1>

<%= render partial: "categories_form", locals: {url: admin_categories_path, button_text: "Create Category"} %>

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>

<%= flash[:login_success] %>

<div class="admin-links-container">
  <%= link_to "Menu Items", admin_menu_items_path, class: "main-link" %>
  <%= link_to "Categories", admin_categories_path, class: "main-link" %>
  <%= link_to "Menu Types", admin_menu_types_path, class: "main-link" %>
</div>

app/views/admin/menu_types/_menu_types_form.html.erb
<ul>
  <% @menu_type.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for @menu_type, url: url do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit button_text %>
<% end %>

app/views/admin/menu_types/edit.html.erb
<h3>Edit <%= @menu_type.name %></h3>

<%= render partial: "menu_types_form", locals: {url: "/admin/menu_types/#{@menu_type.id}", button_text: "Update Menu Type"} %>

app/views/admin/menu_types/index.html.erb
<div class="menu-types-container">
  <h1>Menu Types</h1>

  <%= flash[:menu_type_success] %>

  <%= link_to "Add Menu Type", new_admin_menu_type_path, class: "main-link" %>

  <table>
    <thead>
    <th>Name</th>
    <th></th>
    </thead>
    <tbody>

    <% @menu_types.each do |menu_type| %>
      <tr>
        <td><%= menu_type.name %></td>
        <td>
          <%= link_to "Edit", edit_admin_menu_type_path(menu_type), class: "main-button" %>
          <%= link_to "Delete", admin_menu_type_path(menu_type), method: :delete, class: "main-button" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/menu_types/new.html.erb
<h1>Create a Menu Type</h1>

<%= render partial: "menu_types_form", locals: {url: admin_menu_types_path, button_text: "Create Menu Type"} %>

app/views/categories/index.html.erb
<div class="categories-container">
  <h1>Categories</h1>

  <%= flash[:category_success] %>

  <%= link_to "Add Category", new_category_path %>

  <table>
    <thead>
    <th>Name</th>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h1>Create a Category</h1>

<ul>
  <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create Category" %>
<% end %>

app/views/contact_us/index.html.erb
<section class="contact-information">
  <h3>Contact Us</h3>
  <ul>
    <li>Hunan Springs</li>
    <li>24 E. Kiowa St.</li>
    <li>Colorado Springs, CO 80903</li>
    <li>P: (719) 634-0800</li>
  </ul>
  <h3>Hours</h3>
  <p>Lunch is served from 11:00 a.m. - 3:00 p.m.</p>
  <p>Dinner is served from 3:00 p.m. - close.</p>
  <table class="contact-us">
    <tr>
      <td>Sunday:</td>
      <td>11:00 a.m. - 9:00 p.m.</td>
    </tr>
    <tr>
      <td>Monday:</td>
      <td>11:00 a.m. - 9:00 p.m.</td>
    </tr>
    <tr>
      <td>Tuesday:</td>
      <td>11:00 a.m. - 9:00 p.m.</td>
    </tr>
    <tr>
      <td>Wednesday:</td>
      <td>11:00 a.m. - 9:00 p.m.</td>
    </tr>
    <tr>
      <td>Thursday:</td>
      <td>11:00 a.m. - 9:00 p.m.</td>
    </tr>
    <tr>
      <td>Friday:</td>
      <td>11:00 a.m. - 10:00 p.m.</td>
    </tr>
    <tr>
      <td>Saturday:</td>
      <td>11:00 a.m. - 10:00 p.m.</td>
    </tr>
  </table>
</section>
<section class="hunan-image">
</section>

app/views/menu/_menu_item.html.erb
<section class="<%= category %>-container">
  <h3><%= menu_item.category.name %></h3>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= menu_item.name %></td>
      <td><%= menu_item.description %></td>
      <td><%= number_to_currency(menu_item.price, unit: "$") %></td>
    </tr>
    </tbody>
  </table>
</section>

app/views/menu/_soup_menu_item.html.erb
<section class="soup-container">
  <h3><%= menu_item.category.name %></h3>
  <ul>
    <li><%= menu_item.name %></li>
    <li><%= menu_item.description %></li>
    <li><%= number_to_currency(menu_item.price, unit: "$") %></li>
  </ul>
</section>

app/views/menu/index.html.erb
<div class="menu-container">
  <div class="menu-type-container">
    <%= link_to "Lunch Menu", "/menu?type=lunch", class: "menu-type-link #{@class}" %>
    <%= link_to "Dinner Menu", "/menu?type=dinner", class: "menu-type-link #{@class}" %>
  </div>
  <% @menu_items.each do |menu_item| %>
    <% if menu_item.category.name == "Appetizers" %>
      <%= render partial: "menu_item", locals: {category: "appetizers", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Soup" %>
      <%= render partial: "soup_menu_item", locals: {menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Fried Rice" %>
      <%= render partial: "menu_item", locals: {category: "fried-rice", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Pork" %>
      <%= render partial: "menu_item", locals: {category: "pork", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Beef" %>
      <%= render partial: "menu_item", locals: {category: "beef", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Egg Foo Young" %>
      <%= render partial: "menu_item", locals: {category: "egg-foo-young", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Poultry" %>
      <%= render partial: "menu_item", locals: {category: "poultry", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Seafood" %>
      <%= render partial: "menu_item", locals: {category: "seafood", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Vegetables" %>
      <%= render partial: "menu_item", locals: {category: "vegetables", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Lo Mein and Chow Mein" %>
      <%= render partial: "menu_item", locals: {category: "lo-mein-chow-mein", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Chef Special" %>
      <%= render partial: "menu_item", locals: {category: "chef-special", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Dessert" %>
      <%= render partial: "menu_item", locals: {category: "dessert", menu_item: menu_item} %>
    <% elsif menu_item.category.name == "Beverages" %>
      <%= render partial: "menu_item", locals: {category: "beverages", menu_item: menu_item} %>
    <% end %>
  <% end %>
</div>

app/views/menu_items/index.html.erb
<h1>Menu Items</h1>

<%= flash[:menu_item_success] %>

<%= link_to "Add Menu Item", new_menu_item_path, class: "admin-link" %>

<table>
  <thead>
  <th>Name</th>
  <th>Description</th>
  <th>Price</th>
  <th>Menu Type</th>
  <th>Category</th>
  <th>Size</th>
  </thead>
  <% @menu_items.each do |menu_item| %>
    <tbody>
    <td><%= menu_item.name %></td>
    <td><%= menu_item.description %></td>
    <td><%= number_to_currency(menu_item.price, unit: "$") %></td>
    <td><%= menu_item.menu_type.name %></td>
    <td><%= menu_item.category.name %></td>
    <td><%= menu_item.size.name if menu_item.size %></td>
    </tbody>
  <% end %>
</table>

app/views/menu_items/new.html.erb
<h1>Add Menu Item</h1>

<ul>
  <% @menu_item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for @menu_item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label "Size (if Soup)" %>
  <%= f.collection_select :size_id, @sizes, :id, :name, {include_blank: "Please select a soup size..."} %>
  <%= f.label :menu_type %>
  <%= f.collection_select :menu_type_id, @menu_types, :id, :name, {include_blank: "Please select a menu type..."} %>
  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :name, {include_blank: "Please select a category..."} %>
  <%= f.submit "Create Menu Item" %>
<% end %>

app/views/menu_types/index.html.erb
<div class="menu-types-container">
  <h1>Menu Types</h1>

  <%= flash[:menu_type_success] %>

  <%= link_to "Add Menu Type", new_menu_type_path %>

  <table>
    <thead>
    <th>Name</th>
    </thead>
    <tbody>

    <% @menu_types.each do |menu_type| %>
      <tr>
        <td><%= menu_type.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/menu_types/new.html.erb
<h1>Create a Menu Type</h1>

<ul>
  <% @menu_type.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for @menu_type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create Menu Type" %>
<% end %>

app/views/partials/_admin_nav.html.erb
<nav class="admin-nav">
  <%= link_to "Admin Navigation Bar", admin_path %>
  <ul>
    <li><%= link_to "Dashboard", admin_path %></li>
    <li><%= link_to "Menu Items", admin_menu_items_path %></li>
    <li><%= link_to "Categories", admin_categories_path %></li>
    <li><%= link_to "Menu Types", admin_menu_types_path %></li>
    <li><%= link_to "Logout", "/admin/session", method: :delete %></li>
  </ul>
</nav>

app/views/sizes/index.html.erb
<div class="sizes-container">
  <h1>Sizes</h1>

  <%= flash[:size_success] %>

  <%= link_to "Add Menu Item Size", new_size_path %>

  <table>
    <thead>
    <th>Name</th>
    </thead>
    <tbody>

    <% @sizes.each do |size| %>
      <tr>
        <td><%= size.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/sizes/new.html.erb
<h1>Create a Menu Item Size</h1>

<ul>
  <% @size.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for @size do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create Menu Item Size" %>
<% end %>